# This workflow will install Python dependencies and lint with a single version of Python

name: Lint

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv pip install --system -e ".[dev]"
    - name: Lint
      run: |
        LINT_TARGETS="src/ tests/"
        black --check $LINT_TARGETS
        ruff check $LINT_TARGETS
        isort --check-only $LINT_TARGETS
