name: Official PyPI Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    environment: pypi
    if: github.repository == 'autogluon/autogluon-assistant'
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CICD_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          skip-existing: true
